- name: Install and start Nginx
  hosts: all
  become: yes
  tasks:
  - name: Install Nginx
    apt:
      name: nginx
      state: present

  - name: creating Dir
    file:
      name: new_dir
      state: directory

  - name: creating file
    file:
      name: new_dir/new.txt
      state: touch